name: Build | deploy Node.js app | upload coverage reports - comogastei

on:
  push:
    branches:
      - master
  pull_request:
    branches: master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      
    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '12.13.0'
      
    - name: Install Dependencies
      run: yarn
        
    - name: Run Tests 
      run: yarn test --coverage

    - name: Upload coverage to Codecov
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: bash <(curl -s https://codecov.io/bash)

    
